import moment from "moment";

export const data = [
  {
    errors: null,
    id: 86,
    title: "ưerwer",
    description: null,
    used: false,
    startAt: "2020-08-23T03:00:09.000Z",
    endAt: null,
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-25T02:58:34.250Z",
    updatedAt: "2020-08-25T03:25:30.737Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 85,
    title: "thêm mới",
    description: null,
    used: false,
    startAt: "2020-08-09T02:56:48.000Z",
    endAt: null,
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-25T02:55:12.097Z",
    updatedAt: "2020-08-25T02:55:12.097Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 84,
    title: "Tạo kh",
    description: null,
    used: false,
    startAt: "2020-08-23T02:55:49.000Z",
    endAt: null,
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-25T02:54:13.980Z",
    updatedAt: "2020-08-25T02:54:13.980Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 83,
    title: "Tạo ch khảo sát",
    description: null,
    used: false,
    startAt: "2020-08-23T02:54:33.000Z",
    endAt: null,
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-25T02:53:16.547Z",
    updatedAt: "2020-08-25T02:53:16.547Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 82,
    title: "23423432",
    description: null,
    used: false,
    startAt: "2020-08-23T04:21:44.000Z",
    endAt: null,
    statusId: 2,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-24T04:20:12.167Z",
    updatedAt: "2020-08-24T04:20:12.167Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 2,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 81,
    title: "Thêm mới câu hỏi khảo sát",
    description: null,
    used: false,
    startAt: "2020-08-23T04:17:42.000Z",
    endAt: null,
    statusId: 3,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-24T04:19:39.840Z",
    updatedAt: "2020-08-24T04:19:39.840Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 3,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 80,
    title: "Khao sat huong test",
    description: null,
    used: true,
    startAt: "2020-08-22T02:35:42.000Z",
    endAt: "2020-08-26T02:35:45.000Z",
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-22T02:36:27.217Z",
    updatedAt: "2020-08-22T02:36:27.217Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 79,
    title: "1000",
    description: "111",
    used: false,
    startAt: "2020-08-07T07:49:48.000Z",
    endAt: "2020-08-31T07:49:51.000Z",
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-21T07:51:06.813Z",
    updatedAt: "2020-08-21T07:51:06.813Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 78,
    title: "Nhaapj text",
    description: null,
    used: false,
    startAt: "2020-08-01T09:10:54.000Z",
    endAt: "2020-08-18T09:10:58.000Z",
    statusId: 1,
    creatorId: 2,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-18T09:12:13.043Z",
    updatedAt: "2020-08-18T09:12:13.043Z",
    creator: {
      errors: null,
      id: 2,
      username: "Administrator",
      displayName: "Tôi là admin",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
  {
    errors: null,
    id: 75,
    title: "CÂU HỎI MỚI",
    description: "Mô tả thông tin",
    used: false,
    startAt: "2020-08-09T03:15:09.000Z",
    endAt: "2020-08-22T03:15:13.000Z",
    statusId: 1,
    creatorId: 2786,
    storeId: 0,
    resultCounter: 0,
    surveyQuestions: null,
    createdAt: "2020-08-12T03:14:03.670Z",
    updatedAt: "2020-08-18T09:18:40.750Z",
    creator: {
      errors: null,
      id: 2786,
      username: "TV01.HaDH",
      displayName: "Đỗ Hưng Hà",
    },
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
  },
];
export const dataPayment = [
  {
    id: 100,
    name: 'Đề nghị thanh toán loại 1',
    code: 'TTL1',
    date: moment(),
    province: {
      id: 1001,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 101,
    name: 'Đề nghị thanh toán loại 2',
    code: 'TTL2',
    date: moment(),
    province: {
      id: 1002,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50001,
    status: {
      errors: null,
      id: 2,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 2,
  },
  {
    id: 102,
    name: 'Đề nghị thanh toán loại 3',
    code: 'TTL3',
    date: moment(),
    province: {
      id: 1003,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50002,
    status: {
      errors: null,
      id: 3,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 3,
  },
  {
    id: 103,
    name: 'Đề nghị thanh toán loại 4',
    code: 'TTL4',
    date: moment(),
    province: {
      id: 1004,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 104,
    name: 'Đề nghị thanh toán loại 5',
    code: 'TTL5',
    date: moment(),
    province: {
      id: 1004,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 105,
    name: 'Đề nghị thanh toán loại 6',
    code: 'TTL6',
    date: moment(),
    province: {
      id: 1005,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 2,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 2,
  },
  {
    id: 106,
    name: 'Đề nghị thanh toán loại 7',
    code: 'TTL7',
    date: moment(),
    province: {
      id: 1006,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 107,
    name: 'Đề nghị thanh toán loại 8',
    code: 'TTL8',
    date: moment(),
    province: {
      id: 1007,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 3,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 3,
  },
  {
    id: 108,
    name: 'Đề nghị thanh toán loại 9',
    code: 'TTL9',
    date: moment(),
    province: {
      id: 1009,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 109,
    name: 'Đề nghị thanh toán loại 10',
    code: 'TTL1',
    date: moment(),
    province: {
      id: 1009,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 1,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 1,
  },
  {
    id: 110,
    name: 'Đề nghị thanh toán loại 11',
    code: 'TTL1',
    date: moment(),
    province: {
      id: 1010,
      name: 'Hà Nội',
      code: 'HN',
    },
    paymentDate: moment(),
    paymentNumber: 50000,
    status: {
      errors: null,
      id: 3,
      code: "Active",
      name: "Hoạt động",
    },
    statusId: 3,
  },
];